version: "2"
services:
  postgres:
    image: postgres:12.1
    container_name: postgres
    restart: always
    ports:
      - "5432:5432"
    environment:
      - POSTGRES_DB=postgres
      - POSTGRES_PASSWORD=odoo
      - POSTGRES_USER=odoo
      - PGDATA=/var/lib/postgresql/data/pgdata
    volumes:
      - ./postgresql/data:/var/lib/postgresql/data/pgdata
  odoo:
    image: odoo:13.0
    container_name: odoo
    restart: always
    ports:
      - "8069:8069"
    environment:
      - HOST=postgres
      - PORT=5432
      - USER=odoo
      - PASSWORD=odoo
    volumes:
      - ./odoo/addons:/mnt/extra-addons
      - ./odoo/config:/etc/odoo
      - ./odoo/log:/var/log/odoo
      - ./odoo/data:/var/lib/odoo
    depends_on:
      - postgres
